import Foundation
import RealmSwift

class Deletion: Object {
    
    var deletedFooditems = List<FoodItem>()
    var addedFooditems = List<FoodItem>()
    dynamic var createdAt = NSDate()
    dynamic var mealIndex = 0
    dynamic var numberOfMealsThatDay = 0
    dynamic var autogeneratedDeletion = false
    
    var reasonForDeletion: [String] {
        get {
            return _backingNickNames.map { $0.stringValue }
        }
        set {
            _backingNickNames.removeAll()
            _backingNickNames.appendContentsOf(newValue.map { RealmString(value: [$0]) })
        }
    }
    
    
    let _backingNickNames = List<RealmString>()
    override class func ignoredProperties() -> [String] {
        return ["reasonForDeletion"]
    }


    
//  override static func ignoredProperties() -> [String] {
//  // Specify properties to ignore (Realm won't persist these)
    //return []
//  }
}
