import Foundation
import RealmSwift

class FoodChange: Object {
    
    var deletedFooditems = List<FoodItem>()
    var addedFooditems = List<FoodItem>()
    var editedFooditems = List<FoodItem>()
    dynamic var createdAt = Date()
    dynamic var mealIndex = 0
    dynamic var numberOfMealsThatDay = 0
    dynamic var autogeneratedDeletion = false
    
    var reasonForChange: [String] {
        get {
            return _backingNickNames.map { $0.stringValue }
        }
        set {
            _backingNickNames.removeAll()
            _backingNickNames.append(objectsIn: newValue.map { RealmString(value: [$0]) })
        }
    }
    
    
    let _backingNickNames = List<RealmString>()
    override class func ignoredProperties() -> [String] {
        return ["reasonForChange"]
    }
    
    //taken from: https://github.com/realm/realm-cocoa/issues/2318#issuecomment-126392191
    
    //  override static func ignoredProperties() -> [String] {
    //  // Specify properties to ignore (Realm won't persist these)
    //return []
    //  }
}

